/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DiscordRouteImport } from "./routes/discord";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocsIndexRouteImport } from "./routes/docs/index";
import { Route as ChangelogIndexRouteImport } from "./routes/changelog/index";
import { Route as BlogIndexRouteImport } from "./routes/blog/index";
import { Route as DocsLlmRouteImport } from "./routes/docs/llm";
import { Route as DocsExamplesRouteImport } from "./routes/docs/examples";
import { Route as BlogMovableTreeRouteImport } from "./routes/blog/movable-tree";
import { Route as BlogLoroRichtextRouteImport } from "./routes/blog/loro-richtext";
import { Route as BlogLoroProtocolRouteImport } from "./routes/blog/loro-protocol";
import { Route as BlogLoroOpenSourceRouteImport } from "./routes/blog/loro-open-source";
import { Route as BlogLoroNowOpenSourceRouteImport } from "./routes/blog/loro-now-open-source";
import { Route as BlogLoroMirrorRouteImport } from "./routes/blog/loro-mirror";
import { Route as BlogCrdtRichtextRouteImport } from "./routes/blog/crdt-richtext";
import { Route as DocsPerformanceIndexRouteImport } from "./routes/docs/performance/index";
import { Route as DocsTutorialVersionRouteImport } from "./routes/docs/tutorial/version";
import { Route as DocsTutorialTreeRouteImport } from "./routes/docs/tutorial/tree";
import { Route as DocsTutorialTipsRouteImport } from "./routes/docs/tutorial/tips";
import { Route as DocsTutorialTime_travelRouteImport } from "./routes/docs/tutorial/time_travel";
import { Route as DocsTutorialTextRouteImport } from "./routes/docs/tutorial/text";
import { Route as DocsTutorialSyncRouteImport } from "./routes/docs/tutorial/sync";
import { Route as DocsTutorialPersistenceRouteImport } from "./routes/docs/tutorial/persistence";
import { Route as DocsTutorialMapRouteImport } from "./routes/docs/tutorial/map";
import { Route as DocsTutorialLoro_docRouteImport } from "./routes/docs/tutorial/loro_doc";
import { Route as DocsTutorialListRouteImport } from "./routes/docs/tutorial/list";
import { Route as DocsTutorialGet_startedRouteImport } from "./routes/docs/tutorial/get_started";
import { Route as DocsTutorialEventRouteImport } from "./routes/docs/tutorial/event";
import { Route as DocsTutorialEphemeralRouteImport } from "./routes/docs/tutorial/ephemeral";
import { Route as DocsTutorialEncodingRouteImport } from "./routes/docs/tutorial/encoding";
import { Route as DocsTutorialCursorRouteImport } from "./routes/docs/tutorial/cursor";
import { Route as DocsTutorialCounterRouteImport } from "./routes/docs/tutorial/counter";
import { Route as DocsTutorialCompositionRouteImport } from "./routes/docs/tutorial/composition";
import { Route as DocsPerformanceNativeRouteImport } from "./routes/docs/performance/native";
import { Route as DocsPerformanceDocsizeRouteImport } from "./routes/docs/performance/docsize";
import { Route as DocsConceptsWhen_not_crdtRouteImport } from "./routes/docs/concepts/when_not_crdt";
import { Route as DocsConceptsVersion_vectorRouteImport } from "./routes/docs/concepts/version_vector";
import { Route as DocsConceptsTransaction_modelRouteImport } from "./routes/docs/concepts/transaction_model";
import { Route as DocsConceptsShallow_snapshotsRouteImport } from "./routes/docs/concepts/shallow_snapshots";
import { Route as DocsConceptsPeerid_managementRouteImport } from "./routes/docs/concepts/peerid_management";
import { Route as DocsConceptsOplog_docstateRouteImport } from "./routes/docs/concepts/oplog_docstate";
import { Route as DocsConceptsOperations_changesRouteImport } from "./routes/docs/concepts/operations_changes";
import { Route as DocsConceptsImport_statusRouteImport } from "./routes/docs/concepts/import_status";
import { Route as DocsConceptsFrontiersRouteImport } from "./routes/docs/concepts/frontiers";
import { Route as DocsConceptsEvent_graph_walkerRouteImport } from "./routes/docs/concepts/event_graph_walker";
import { Route as DocsConceptsCursor_stable_positionsRouteImport } from "./routes/docs/concepts/cursor_stable_positions";
import { Route as DocsConceptsCrdtRouteImport } from "./routes/docs/concepts/crdt";
import { Route as DocsConceptsContainerRouteImport } from "./routes/docs/concepts/container";
import { Route as DocsConceptsChoose_crdt_typeRouteImport } from "./routes/docs/concepts/choose_crdt_type";
import { Route as DocsConceptsAttached_detachedRouteImport } from "./routes/docs/concepts/attached_detached";
import { Route as DocsApiJsRouteImport } from "./routes/docs/api/js";
import { Route as DocsAdvancedVersion_deep_diveRouteImport } from "./routes/docs/advanced/version_deep_dive";
import { Route as DocsAdvancedUndoRouteImport } from "./routes/docs/advanced/undo";
import { Route as DocsAdvancedTimestampRouteImport } from "./routes/docs/advanced/timestamp";
import { Route as DocsAdvancedShallow_snapshotRouteImport } from "./routes/docs/advanced/shallow_snapshot";
import { Route as DocsAdvancedReplayable_event_graphRouteImport } from "./routes/docs/advanced/replayable_event_graph";
import { Route as DocsAdvancedOp_and_changeRouteImport } from "./routes/docs/advanced/op_and_change";
import { Route as DocsAdvancedJsonpathRouteImport } from "./routes/docs/advanced/jsonpath";
import { Route as DocsAdvancedInspectorRouteImport } from "./routes/docs/advanced/inspector";
import { Route as DocsAdvancedImport_batchRouteImport } from "./routes/docs/advanced/import_batch";
import { Route as DocsAdvancedEvent_graph_walkerRouteImport } from "./routes/docs/advanced/event_graph_walker";
import { Route as DocsAdvancedDoc_state_and_oplogRouteImport } from "./routes/docs/advanced/doc_state_and_oplog";
import { Route as DocsAdvancedCidRouteImport } from "./routes/docs/advanced/cid";
import { Route as BlogV10RouteImport } from "./routes/blog/v1.0";
import { Route as ChangelogV190RouteImport } from "./routes/changelog/v1.9.0";
import { Route as ChangelogV180RouteImport } from "./routes/changelog/v1.8.0";
import { Route as ChangelogV160RouteImport } from "./routes/changelog/v1.6.0";
import { Route as ChangelogV150RouteImport } from "./routes/changelog/v1.5.0";
import { Route as ChangelogV147RouteImport } from "./routes/changelog/v1.4.7";
import { Route as ChangelogV140RouteImport } from "./routes/changelog/v1.4.0";
import { Route as ChangelogV130RouteImport } from "./routes/changelog/v1.3.0";
import { Route as ChangelogV120RouteImport } from "./routes/changelog/v1.2.0";
import { Route as ChangelogV110RouteImport } from "./routes/changelog/v1.1.0";
import { Route as ChangelogV100BetaRouteImport } from "./routes/changelog/v1.0.0-beta";
import { Route as ChangelogInspectorV010RouteImport } from "./routes/changelog/inspector-v0.1.0";

const DiscordRoute = DiscordRouteImport.update({
  id: "/discord",
  path: "/discord",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: "/changelog/",
  path: "/changelog/",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsLlmRoute = DocsLlmRouteImport.update({
  id: "/docs/llm",
  path: "/docs/llm",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: "/docs/examples",
  path: "/docs/examples",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogMovableTreeRoute = BlogMovableTreeRouteImport.update({
  id: "/blog/movable-tree",
  path: "/blog/movable-tree",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogLoroRichtextRoute = BlogLoroRichtextRouteImport.update({
  id: "/blog/loro-richtext",
  path: "/blog/loro-richtext",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogLoroProtocolRoute = BlogLoroProtocolRouteImport.update({
  id: "/blog/loro-protocol",
  path: "/blog/loro-protocol",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogLoroOpenSourceRoute = BlogLoroOpenSourceRouteImport.update({
  id: "/blog/loro-open-source",
  path: "/blog/loro-open-source",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogLoroNowOpenSourceRoute = BlogLoroNowOpenSourceRouteImport.update({
  id: "/blog/loro-now-open-source",
  path: "/blog/loro-now-open-source",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogLoroMirrorRoute = BlogLoroMirrorRouteImport.update({
  id: "/blog/loro-mirror",
  path: "/blog/loro-mirror",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogCrdtRichtextRoute = BlogCrdtRichtextRouteImport.update({
  id: "/blog/crdt-richtext",
  path: "/blog/crdt-richtext",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsPerformanceIndexRoute = DocsPerformanceIndexRouteImport.update({
  id: "/docs/performance/",
  path: "/docs/performance/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialVersionRoute = DocsTutorialVersionRouteImport.update({
  id: "/docs/tutorial/version",
  path: "/docs/tutorial/version",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialTreeRoute = DocsTutorialTreeRouteImport.update({
  id: "/docs/tutorial/tree",
  path: "/docs/tutorial/tree",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialTipsRoute = DocsTutorialTipsRouteImport.update({
  id: "/docs/tutorial/tips",
  path: "/docs/tutorial/tips",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialTime_travelRoute = DocsTutorialTime_travelRouteImport.update({
  id: "/docs/tutorial/time_travel",
  path: "/docs/tutorial/time_travel",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialTextRoute = DocsTutorialTextRouteImport.update({
  id: "/docs/tutorial/text",
  path: "/docs/tutorial/text",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialSyncRoute = DocsTutorialSyncRouteImport.update({
  id: "/docs/tutorial/sync",
  path: "/docs/tutorial/sync",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialPersistenceRoute = DocsTutorialPersistenceRouteImport.update({
  id: "/docs/tutorial/persistence",
  path: "/docs/tutorial/persistence",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialMapRoute = DocsTutorialMapRouteImport.update({
  id: "/docs/tutorial/map",
  path: "/docs/tutorial/map",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialLoro_docRoute = DocsTutorialLoro_docRouteImport.update({
  id: "/docs/tutorial/loro_doc",
  path: "/docs/tutorial/loro_doc",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialListRoute = DocsTutorialListRouteImport.update({
  id: "/docs/tutorial/list",
  path: "/docs/tutorial/list",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialGet_startedRoute = DocsTutorialGet_startedRouteImport.update({
  id: "/docs/tutorial/get_started",
  path: "/docs/tutorial/get_started",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialEventRoute = DocsTutorialEventRouteImport.update({
  id: "/docs/tutorial/event",
  path: "/docs/tutorial/event",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialEphemeralRoute = DocsTutorialEphemeralRouteImport.update({
  id: "/docs/tutorial/ephemeral",
  path: "/docs/tutorial/ephemeral",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialEncodingRoute = DocsTutorialEncodingRouteImport.update({
  id: "/docs/tutorial/encoding",
  path: "/docs/tutorial/encoding",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialCursorRoute = DocsTutorialCursorRouteImport.update({
  id: "/docs/tutorial/cursor",
  path: "/docs/tutorial/cursor",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialCounterRoute = DocsTutorialCounterRouteImport.update({
  id: "/docs/tutorial/counter",
  path: "/docs/tutorial/counter",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsTutorialCompositionRoute = DocsTutorialCompositionRouteImport.update({
  id: "/docs/tutorial/composition",
  path: "/docs/tutorial/composition",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsPerformanceNativeRoute = DocsPerformanceNativeRouteImport.update({
  id: "/docs/performance/native",
  path: "/docs/performance/native",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsPerformanceDocsizeRoute = DocsPerformanceDocsizeRouteImport.update({
  id: "/docs/performance/docsize",
  path: "/docs/performance/docsize",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsConceptsWhen_not_crdtRoute =
  DocsConceptsWhen_not_crdtRouteImport.update({
    id: "/docs/concepts/when_not_crdt",
    path: "/docs/concepts/when_not_crdt",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsVersion_vectorRoute =
  DocsConceptsVersion_vectorRouteImport.update({
    id: "/docs/concepts/version_vector",
    path: "/docs/concepts/version_vector",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsTransaction_modelRoute =
  DocsConceptsTransaction_modelRouteImport.update({
    id: "/docs/concepts/transaction_model",
    path: "/docs/concepts/transaction_model",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsShallow_snapshotsRoute =
  DocsConceptsShallow_snapshotsRouteImport.update({
    id: "/docs/concepts/shallow_snapshots",
    path: "/docs/concepts/shallow_snapshots",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsPeerid_managementRoute =
  DocsConceptsPeerid_managementRouteImport.update({
    id: "/docs/concepts/peerid_management",
    path: "/docs/concepts/peerid_management",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsOplog_docstateRoute =
  DocsConceptsOplog_docstateRouteImport.update({
    id: "/docs/concepts/oplog_docstate",
    path: "/docs/concepts/oplog_docstate",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsOperations_changesRoute =
  DocsConceptsOperations_changesRouteImport.update({
    id: "/docs/concepts/operations_changes",
    path: "/docs/concepts/operations_changes",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsImport_statusRoute =
  DocsConceptsImport_statusRouteImport.update({
    id: "/docs/concepts/import_status",
    path: "/docs/concepts/import_status",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsFrontiersRoute = DocsConceptsFrontiersRouteImport.update({
  id: "/docs/concepts/frontiers",
  path: "/docs/concepts/frontiers",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsConceptsEvent_graph_walkerRoute =
  DocsConceptsEvent_graph_walkerRouteImport.update({
    id: "/docs/concepts/event_graph_walker",
    path: "/docs/concepts/event_graph_walker",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsCursor_stable_positionsRoute =
  DocsConceptsCursor_stable_positionsRouteImport.update({
    id: "/docs/concepts/cursor_stable_positions",
    path: "/docs/concepts/cursor_stable_positions",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsCrdtRoute = DocsConceptsCrdtRouteImport.update({
  id: "/docs/concepts/crdt",
  path: "/docs/concepts/crdt",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsConceptsContainerRoute = DocsConceptsContainerRouteImport.update({
  id: "/docs/concepts/container",
  path: "/docs/concepts/container",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsConceptsChoose_crdt_typeRoute =
  DocsConceptsChoose_crdt_typeRouteImport.update({
    id: "/docs/concepts/choose_crdt_type",
    path: "/docs/concepts/choose_crdt_type",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsConceptsAttached_detachedRoute =
  DocsConceptsAttached_detachedRouteImport.update({
    id: "/docs/concepts/attached_detached",
    path: "/docs/concepts/attached_detached",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsApiJsRoute = DocsApiJsRouteImport.update({
  id: "/docs/api/js",
  path: "/docs/api/js",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsAdvancedVersion_deep_diveRoute =
  DocsAdvancedVersion_deep_diveRouteImport.update({
    id: "/docs/advanced/version_deep_dive",
    path: "/docs/advanced/version_deep_dive",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedUndoRoute = DocsAdvancedUndoRouteImport.update({
  id: "/docs/advanced/undo",
  path: "/docs/advanced/undo",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsAdvancedTimestampRoute = DocsAdvancedTimestampRouteImport.update({
  id: "/docs/advanced/timestamp",
  path: "/docs/advanced/timestamp",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsAdvancedShallow_snapshotRoute =
  DocsAdvancedShallow_snapshotRouteImport.update({
    id: "/docs/advanced/shallow_snapshot",
    path: "/docs/advanced/shallow_snapshot",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedReplayable_event_graphRoute =
  DocsAdvancedReplayable_event_graphRouteImport.update({
    id: "/docs/advanced/replayable_event_graph",
    path: "/docs/advanced/replayable_event_graph",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedOp_and_changeRoute =
  DocsAdvancedOp_and_changeRouteImport.update({
    id: "/docs/advanced/op_and_change",
    path: "/docs/advanced/op_and_change",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedJsonpathRoute = DocsAdvancedJsonpathRouteImport.update({
  id: "/docs/advanced/jsonpath",
  path: "/docs/advanced/jsonpath",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsAdvancedInspectorRoute = DocsAdvancedInspectorRouteImport.update({
  id: "/docs/advanced/inspector",
  path: "/docs/advanced/inspector",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsAdvancedImport_batchRoute =
  DocsAdvancedImport_batchRouteImport.update({
    id: "/docs/advanced/import_batch",
    path: "/docs/advanced/import_batch",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedEvent_graph_walkerRoute =
  DocsAdvancedEvent_graph_walkerRouteImport.update({
    id: "/docs/advanced/event_graph_walker",
    path: "/docs/advanced/event_graph_walker",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedDoc_state_and_oplogRoute =
  DocsAdvancedDoc_state_and_oplogRouteImport.update({
    id: "/docs/advanced/doc_state_and_oplog",
    path: "/docs/advanced/doc_state_and_oplog",
    getParentRoute: () => rootRouteImport,
  } as any);
const DocsAdvancedCidRoute = DocsAdvancedCidRouteImport.update({
  id: "/docs/advanced/cid",
  path: "/docs/advanced/cid",
  getParentRoute: () => rootRouteImport,
} as any);
const BlogV10Route = BlogV10RouteImport.update({
  id: "/blog/v1/0",
  path: "/blog/v1/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV190Route = ChangelogV190RouteImport.update({
  id: "/changelog/v1/9/0",
  path: "/changelog/v1/9/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV180Route = ChangelogV180RouteImport.update({
  id: "/changelog/v1/8/0",
  path: "/changelog/v1/8/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV160Route = ChangelogV160RouteImport.update({
  id: "/changelog/v1/6/0",
  path: "/changelog/v1/6/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV150Route = ChangelogV150RouteImport.update({
  id: "/changelog/v1/5/0",
  path: "/changelog/v1/5/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV147Route = ChangelogV147RouteImport.update({
  id: "/changelog/v1/4/7",
  path: "/changelog/v1/4/7",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV140Route = ChangelogV140RouteImport.update({
  id: "/changelog/v1/4/0",
  path: "/changelog/v1/4/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV130Route = ChangelogV130RouteImport.update({
  id: "/changelog/v1/3/0",
  path: "/changelog/v1/3/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV120Route = ChangelogV120RouteImport.update({
  id: "/changelog/v1/2/0",
  path: "/changelog/v1/2/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV110Route = ChangelogV110RouteImport.update({
  id: "/changelog/v1/1/0",
  path: "/changelog/v1/1/0",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogV100BetaRoute = ChangelogV100BetaRouteImport.update({
  id: "/changelog/v1/0/0-beta",
  path: "/changelog/v1/0/0-beta",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogInspectorV010Route = ChangelogInspectorV010RouteImport.update({
  id: "/changelog/inspector-v0/1/0",
  path: "/changelog/inspector-v0/1/0",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discord": typeof DiscordRoute;
  "/blog/crdt-richtext": typeof BlogCrdtRichtextRoute;
  "/blog/loro-mirror": typeof BlogLoroMirrorRoute;
  "/blog/loro-now-open-source": typeof BlogLoroNowOpenSourceRoute;
  "/blog/loro-open-source": typeof BlogLoroOpenSourceRoute;
  "/blog/loro-protocol": typeof BlogLoroProtocolRoute;
  "/blog/loro-richtext": typeof BlogLoroRichtextRoute;
  "/blog/movable-tree": typeof BlogMovableTreeRoute;
  "/docs/examples": typeof DocsExamplesRoute;
  "/docs/llm": typeof DocsLlmRoute;
  "/blog/": typeof BlogIndexRoute;
  "/changelog/": typeof ChangelogIndexRoute;
  "/docs/": typeof DocsIndexRoute;
  "/blog/v1/0": typeof BlogV10Route;
  "/docs/advanced/cid": typeof DocsAdvancedCidRoute;
  "/docs/advanced/doc_state_and_oplog": typeof DocsAdvancedDoc_state_and_oplogRoute;
  "/docs/advanced/event_graph_walker": typeof DocsAdvancedEvent_graph_walkerRoute;
  "/docs/advanced/import_batch": typeof DocsAdvancedImport_batchRoute;
  "/docs/advanced/inspector": typeof DocsAdvancedInspectorRoute;
  "/docs/advanced/jsonpath": typeof DocsAdvancedJsonpathRoute;
  "/docs/advanced/op_and_change": typeof DocsAdvancedOp_and_changeRoute;
  "/docs/advanced/replayable_event_graph": typeof DocsAdvancedReplayable_event_graphRoute;
  "/docs/advanced/shallow_snapshot": typeof DocsAdvancedShallow_snapshotRoute;
  "/docs/advanced/timestamp": typeof DocsAdvancedTimestampRoute;
  "/docs/advanced/undo": typeof DocsAdvancedUndoRoute;
  "/docs/advanced/version_deep_dive": typeof DocsAdvancedVersion_deep_diveRoute;
  "/docs/api/js": typeof DocsApiJsRoute;
  "/docs/concepts/attached_detached": typeof DocsConceptsAttached_detachedRoute;
  "/docs/concepts/choose_crdt_type": typeof DocsConceptsChoose_crdt_typeRoute;
  "/docs/concepts/container": typeof DocsConceptsContainerRoute;
  "/docs/concepts/crdt": typeof DocsConceptsCrdtRoute;
  "/docs/concepts/cursor_stable_positions": typeof DocsConceptsCursor_stable_positionsRoute;
  "/docs/concepts/event_graph_walker": typeof DocsConceptsEvent_graph_walkerRoute;
  "/docs/concepts/frontiers": typeof DocsConceptsFrontiersRoute;
  "/docs/concepts/import_status": typeof DocsConceptsImport_statusRoute;
  "/docs/concepts/operations_changes": typeof DocsConceptsOperations_changesRoute;
  "/docs/concepts/oplog_docstate": typeof DocsConceptsOplog_docstateRoute;
  "/docs/concepts/peerid_management": typeof DocsConceptsPeerid_managementRoute;
  "/docs/concepts/shallow_snapshots": typeof DocsConceptsShallow_snapshotsRoute;
  "/docs/concepts/transaction_model": typeof DocsConceptsTransaction_modelRoute;
  "/docs/concepts/version_vector": typeof DocsConceptsVersion_vectorRoute;
  "/docs/concepts/when_not_crdt": typeof DocsConceptsWhen_not_crdtRoute;
  "/docs/performance/docsize": typeof DocsPerformanceDocsizeRoute;
  "/docs/performance/native": typeof DocsPerformanceNativeRoute;
  "/docs/tutorial/composition": typeof DocsTutorialCompositionRoute;
  "/docs/tutorial/counter": typeof DocsTutorialCounterRoute;
  "/docs/tutorial/cursor": typeof DocsTutorialCursorRoute;
  "/docs/tutorial/encoding": typeof DocsTutorialEncodingRoute;
  "/docs/tutorial/ephemeral": typeof DocsTutorialEphemeralRoute;
  "/docs/tutorial/event": typeof DocsTutorialEventRoute;
  "/docs/tutorial/get_started": typeof DocsTutorialGet_startedRoute;
  "/docs/tutorial/list": typeof DocsTutorialListRoute;
  "/docs/tutorial/loro_doc": typeof DocsTutorialLoro_docRoute;
  "/docs/tutorial/map": typeof DocsTutorialMapRoute;
  "/docs/tutorial/persistence": typeof DocsTutorialPersistenceRoute;
  "/docs/tutorial/sync": typeof DocsTutorialSyncRoute;
  "/docs/tutorial/text": typeof DocsTutorialTextRoute;
  "/docs/tutorial/time_travel": typeof DocsTutorialTime_travelRoute;
  "/docs/tutorial/tips": typeof DocsTutorialTipsRoute;
  "/docs/tutorial/tree": typeof DocsTutorialTreeRoute;
  "/docs/tutorial/version": typeof DocsTutorialVersionRoute;
  "/docs/performance/": typeof DocsPerformanceIndexRoute;
  "/changelog/inspector-v0/1/0": typeof ChangelogInspectorV010Route;
  "/changelog/v1/0/0-beta": typeof ChangelogV100BetaRoute;
  "/changelog/v1/1/0": typeof ChangelogV110Route;
  "/changelog/v1/2/0": typeof ChangelogV120Route;
  "/changelog/v1/3/0": typeof ChangelogV130Route;
  "/changelog/v1/4/0": typeof ChangelogV140Route;
  "/changelog/v1/4/7": typeof ChangelogV147Route;
  "/changelog/v1/5/0": typeof ChangelogV150Route;
  "/changelog/v1/6/0": typeof ChangelogV160Route;
  "/changelog/v1/8/0": typeof ChangelogV180Route;
  "/changelog/v1/9/0": typeof ChangelogV190Route;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discord": typeof DiscordRoute;
  "/blog/crdt-richtext": typeof BlogCrdtRichtextRoute;
  "/blog/loro-mirror": typeof BlogLoroMirrorRoute;
  "/blog/loro-now-open-source": typeof BlogLoroNowOpenSourceRoute;
  "/blog/loro-open-source": typeof BlogLoroOpenSourceRoute;
  "/blog/loro-protocol": typeof BlogLoroProtocolRoute;
  "/blog/loro-richtext": typeof BlogLoroRichtextRoute;
  "/blog/movable-tree": typeof BlogMovableTreeRoute;
  "/docs/examples": typeof DocsExamplesRoute;
  "/docs/llm": typeof DocsLlmRoute;
  "/blog": typeof BlogIndexRoute;
  "/changelog": typeof ChangelogIndexRoute;
  "/docs": typeof DocsIndexRoute;
  "/blog/v1/0": typeof BlogV10Route;
  "/docs/advanced/cid": typeof DocsAdvancedCidRoute;
  "/docs/advanced/doc_state_and_oplog": typeof DocsAdvancedDoc_state_and_oplogRoute;
  "/docs/advanced/event_graph_walker": typeof DocsAdvancedEvent_graph_walkerRoute;
  "/docs/advanced/import_batch": typeof DocsAdvancedImport_batchRoute;
  "/docs/advanced/inspector": typeof DocsAdvancedInspectorRoute;
  "/docs/advanced/jsonpath": typeof DocsAdvancedJsonpathRoute;
  "/docs/advanced/op_and_change": typeof DocsAdvancedOp_and_changeRoute;
  "/docs/advanced/replayable_event_graph": typeof DocsAdvancedReplayable_event_graphRoute;
  "/docs/advanced/shallow_snapshot": typeof DocsAdvancedShallow_snapshotRoute;
  "/docs/advanced/timestamp": typeof DocsAdvancedTimestampRoute;
  "/docs/advanced/undo": typeof DocsAdvancedUndoRoute;
  "/docs/advanced/version_deep_dive": typeof DocsAdvancedVersion_deep_diveRoute;
  "/docs/api/js": typeof DocsApiJsRoute;
  "/docs/concepts/attached_detached": typeof DocsConceptsAttached_detachedRoute;
  "/docs/concepts/choose_crdt_type": typeof DocsConceptsChoose_crdt_typeRoute;
  "/docs/concepts/container": typeof DocsConceptsContainerRoute;
  "/docs/concepts/crdt": typeof DocsConceptsCrdtRoute;
  "/docs/concepts/cursor_stable_positions": typeof DocsConceptsCursor_stable_positionsRoute;
  "/docs/concepts/event_graph_walker": typeof DocsConceptsEvent_graph_walkerRoute;
  "/docs/concepts/frontiers": typeof DocsConceptsFrontiersRoute;
  "/docs/concepts/import_status": typeof DocsConceptsImport_statusRoute;
  "/docs/concepts/operations_changes": typeof DocsConceptsOperations_changesRoute;
  "/docs/concepts/oplog_docstate": typeof DocsConceptsOplog_docstateRoute;
  "/docs/concepts/peerid_management": typeof DocsConceptsPeerid_managementRoute;
  "/docs/concepts/shallow_snapshots": typeof DocsConceptsShallow_snapshotsRoute;
  "/docs/concepts/transaction_model": typeof DocsConceptsTransaction_modelRoute;
  "/docs/concepts/version_vector": typeof DocsConceptsVersion_vectorRoute;
  "/docs/concepts/when_not_crdt": typeof DocsConceptsWhen_not_crdtRoute;
  "/docs/performance/docsize": typeof DocsPerformanceDocsizeRoute;
  "/docs/performance/native": typeof DocsPerformanceNativeRoute;
  "/docs/tutorial/composition": typeof DocsTutorialCompositionRoute;
  "/docs/tutorial/counter": typeof DocsTutorialCounterRoute;
  "/docs/tutorial/cursor": typeof DocsTutorialCursorRoute;
  "/docs/tutorial/encoding": typeof DocsTutorialEncodingRoute;
  "/docs/tutorial/ephemeral": typeof DocsTutorialEphemeralRoute;
  "/docs/tutorial/event": typeof DocsTutorialEventRoute;
  "/docs/tutorial/get_started": typeof DocsTutorialGet_startedRoute;
  "/docs/tutorial/list": typeof DocsTutorialListRoute;
  "/docs/tutorial/loro_doc": typeof DocsTutorialLoro_docRoute;
  "/docs/tutorial/map": typeof DocsTutorialMapRoute;
  "/docs/tutorial/persistence": typeof DocsTutorialPersistenceRoute;
  "/docs/tutorial/sync": typeof DocsTutorialSyncRoute;
  "/docs/tutorial/text": typeof DocsTutorialTextRoute;
  "/docs/tutorial/time_travel": typeof DocsTutorialTime_travelRoute;
  "/docs/tutorial/tips": typeof DocsTutorialTipsRoute;
  "/docs/tutorial/tree": typeof DocsTutorialTreeRoute;
  "/docs/tutorial/version": typeof DocsTutorialVersionRoute;
  "/docs/performance": typeof DocsPerformanceIndexRoute;
  "/changelog/inspector-v0/1/0": typeof ChangelogInspectorV010Route;
  "/changelog/v1/0/0-beta": typeof ChangelogV100BetaRoute;
  "/changelog/v1/1/0": typeof ChangelogV110Route;
  "/changelog/v1/2/0": typeof ChangelogV120Route;
  "/changelog/v1/3/0": typeof ChangelogV130Route;
  "/changelog/v1/4/0": typeof ChangelogV140Route;
  "/changelog/v1/4/7": typeof ChangelogV147Route;
  "/changelog/v1/5/0": typeof ChangelogV150Route;
  "/changelog/v1/6/0": typeof ChangelogV160Route;
  "/changelog/v1/8/0": typeof ChangelogV180Route;
  "/changelog/v1/9/0": typeof ChangelogV190Route;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discord": typeof DiscordRoute;
  "/blog/crdt-richtext": typeof BlogCrdtRichtextRoute;
  "/blog/loro-mirror": typeof BlogLoroMirrorRoute;
  "/blog/loro-now-open-source": typeof BlogLoroNowOpenSourceRoute;
  "/blog/loro-open-source": typeof BlogLoroOpenSourceRoute;
  "/blog/loro-protocol": typeof BlogLoroProtocolRoute;
  "/blog/loro-richtext": typeof BlogLoroRichtextRoute;
  "/blog/movable-tree": typeof BlogMovableTreeRoute;
  "/docs/examples": typeof DocsExamplesRoute;
  "/docs/llm": typeof DocsLlmRoute;
  "/blog/": typeof BlogIndexRoute;
  "/changelog/": typeof ChangelogIndexRoute;
  "/docs/": typeof DocsIndexRoute;
  "/blog/v1/0": typeof BlogV10Route;
  "/docs/advanced/cid": typeof DocsAdvancedCidRoute;
  "/docs/advanced/doc_state_and_oplog": typeof DocsAdvancedDoc_state_and_oplogRoute;
  "/docs/advanced/event_graph_walker": typeof DocsAdvancedEvent_graph_walkerRoute;
  "/docs/advanced/import_batch": typeof DocsAdvancedImport_batchRoute;
  "/docs/advanced/inspector": typeof DocsAdvancedInspectorRoute;
  "/docs/advanced/jsonpath": typeof DocsAdvancedJsonpathRoute;
  "/docs/advanced/op_and_change": typeof DocsAdvancedOp_and_changeRoute;
  "/docs/advanced/replayable_event_graph": typeof DocsAdvancedReplayable_event_graphRoute;
  "/docs/advanced/shallow_snapshot": typeof DocsAdvancedShallow_snapshotRoute;
  "/docs/advanced/timestamp": typeof DocsAdvancedTimestampRoute;
  "/docs/advanced/undo": typeof DocsAdvancedUndoRoute;
  "/docs/advanced/version_deep_dive": typeof DocsAdvancedVersion_deep_diveRoute;
  "/docs/api/js": typeof DocsApiJsRoute;
  "/docs/concepts/attached_detached": typeof DocsConceptsAttached_detachedRoute;
  "/docs/concepts/choose_crdt_type": typeof DocsConceptsChoose_crdt_typeRoute;
  "/docs/concepts/container": typeof DocsConceptsContainerRoute;
  "/docs/concepts/crdt": typeof DocsConceptsCrdtRoute;
  "/docs/concepts/cursor_stable_positions": typeof DocsConceptsCursor_stable_positionsRoute;
  "/docs/concepts/event_graph_walker": typeof DocsConceptsEvent_graph_walkerRoute;
  "/docs/concepts/frontiers": typeof DocsConceptsFrontiersRoute;
  "/docs/concepts/import_status": typeof DocsConceptsImport_statusRoute;
  "/docs/concepts/operations_changes": typeof DocsConceptsOperations_changesRoute;
  "/docs/concepts/oplog_docstate": typeof DocsConceptsOplog_docstateRoute;
  "/docs/concepts/peerid_management": typeof DocsConceptsPeerid_managementRoute;
  "/docs/concepts/shallow_snapshots": typeof DocsConceptsShallow_snapshotsRoute;
  "/docs/concepts/transaction_model": typeof DocsConceptsTransaction_modelRoute;
  "/docs/concepts/version_vector": typeof DocsConceptsVersion_vectorRoute;
  "/docs/concepts/when_not_crdt": typeof DocsConceptsWhen_not_crdtRoute;
  "/docs/performance/docsize": typeof DocsPerformanceDocsizeRoute;
  "/docs/performance/native": typeof DocsPerformanceNativeRoute;
  "/docs/tutorial/composition": typeof DocsTutorialCompositionRoute;
  "/docs/tutorial/counter": typeof DocsTutorialCounterRoute;
  "/docs/tutorial/cursor": typeof DocsTutorialCursorRoute;
  "/docs/tutorial/encoding": typeof DocsTutorialEncodingRoute;
  "/docs/tutorial/ephemeral": typeof DocsTutorialEphemeralRoute;
  "/docs/tutorial/event": typeof DocsTutorialEventRoute;
  "/docs/tutorial/get_started": typeof DocsTutorialGet_startedRoute;
  "/docs/tutorial/list": typeof DocsTutorialListRoute;
  "/docs/tutorial/loro_doc": typeof DocsTutorialLoro_docRoute;
  "/docs/tutorial/map": typeof DocsTutorialMapRoute;
  "/docs/tutorial/persistence": typeof DocsTutorialPersistenceRoute;
  "/docs/tutorial/sync": typeof DocsTutorialSyncRoute;
  "/docs/tutorial/text": typeof DocsTutorialTextRoute;
  "/docs/tutorial/time_travel": typeof DocsTutorialTime_travelRoute;
  "/docs/tutorial/tips": typeof DocsTutorialTipsRoute;
  "/docs/tutorial/tree": typeof DocsTutorialTreeRoute;
  "/docs/tutorial/version": typeof DocsTutorialVersionRoute;
  "/docs/performance/": typeof DocsPerformanceIndexRoute;
  "/changelog/inspector-v0/1/0": typeof ChangelogInspectorV010Route;
  "/changelog/v1/0/0-beta": typeof ChangelogV100BetaRoute;
  "/changelog/v1/1/0": typeof ChangelogV110Route;
  "/changelog/v1/2/0": typeof ChangelogV120Route;
  "/changelog/v1/3/0": typeof ChangelogV130Route;
  "/changelog/v1/4/0": typeof ChangelogV140Route;
  "/changelog/v1/4/7": typeof ChangelogV147Route;
  "/changelog/v1/5/0": typeof ChangelogV150Route;
  "/changelog/v1/6/0": typeof ChangelogV160Route;
  "/changelog/v1/8/0": typeof ChangelogV180Route;
  "/changelog/v1/9/0": typeof ChangelogV190Route;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/discord"
    | "/blog/crdt-richtext"
    | "/blog/loro-mirror"
    | "/blog/loro-now-open-source"
    | "/blog/loro-open-source"
    | "/blog/loro-protocol"
    | "/blog/loro-richtext"
    | "/blog/movable-tree"
    | "/docs/examples"
    | "/docs/llm"
    | "/blog/"
    | "/changelog/"
    | "/docs/"
    | "/blog/v1/0"
    | "/docs/advanced/cid"
    | "/docs/advanced/doc_state_and_oplog"
    | "/docs/advanced/event_graph_walker"
    | "/docs/advanced/import_batch"
    | "/docs/advanced/inspector"
    | "/docs/advanced/jsonpath"
    | "/docs/advanced/op_and_change"
    | "/docs/advanced/replayable_event_graph"
    | "/docs/advanced/shallow_snapshot"
    | "/docs/advanced/timestamp"
    | "/docs/advanced/undo"
    | "/docs/advanced/version_deep_dive"
    | "/docs/api/js"
    | "/docs/concepts/attached_detached"
    | "/docs/concepts/choose_crdt_type"
    | "/docs/concepts/container"
    | "/docs/concepts/crdt"
    | "/docs/concepts/cursor_stable_positions"
    | "/docs/concepts/event_graph_walker"
    | "/docs/concepts/frontiers"
    | "/docs/concepts/import_status"
    | "/docs/concepts/operations_changes"
    | "/docs/concepts/oplog_docstate"
    | "/docs/concepts/peerid_management"
    | "/docs/concepts/shallow_snapshots"
    | "/docs/concepts/transaction_model"
    | "/docs/concepts/version_vector"
    | "/docs/concepts/when_not_crdt"
    | "/docs/performance/docsize"
    | "/docs/performance/native"
    | "/docs/tutorial/composition"
    | "/docs/tutorial/counter"
    | "/docs/tutorial/cursor"
    | "/docs/tutorial/encoding"
    | "/docs/tutorial/ephemeral"
    | "/docs/tutorial/event"
    | "/docs/tutorial/get_started"
    | "/docs/tutorial/list"
    | "/docs/tutorial/loro_doc"
    | "/docs/tutorial/map"
    | "/docs/tutorial/persistence"
    | "/docs/tutorial/sync"
    | "/docs/tutorial/text"
    | "/docs/tutorial/time_travel"
    | "/docs/tutorial/tips"
    | "/docs/tutorial/tree"
    | "/docs/tutorial/version"
    | "/docs/performance/"
    | "/changelog/inspector-v0/1/0"
    | "/changelog/v1/0/0-beta"
    | "/changelog/v1/1/0"
    | "/changelog/v1/2/0"
    | "/changelog/v1/3/0"
    | "/changelog/v1/4/0"
    | "/changelog/v1/4/7"
    | "/changelog/v1/5/0"
    | "/changelog/v1/6/0"
    | "/changelog/v1/8/0"
    | "/changelog/v1/9/0";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/discord"
    | "/blog/crdt-richtext"
    | "/blog/loro-mirror"
    | "/blog/loro-now-open-source"
    | "/blog/loro-open-source"
    | "/blog/loro-protocol"
    | "/blog/loro-richtext"
    | "/blog/movable-tree"
    | "/docs/examples"
    | "/docs/llm"
    | "/blog"
    | "/changelog"
    | "/docs"
    | "/blog/v1/0"
    | "/docs/advanced/cid"
    | "/docs/advanced/doc_state_and_oplog"
    | "/docs/advanced/event_graph_walker"
    | "/docs/advanced/import_batch"
    | "/docs/advanced/inspector"
    | "/docs/advanced/jsonpath"
    | "/docs/advanced/op_and_change"
    | "/docs/advanced/replayable_event_graph"
    | "/docs/advanced/shallow_snapshot"
    | "/docs/advanced/timestamp"
    | "/docs/advanced/undo"
    | "/docs/advanced/version_deep_dive"
    | "/docs/api/js"
    | "/docs/concepts/attached_detached"
    | "/docs/concepts/choose_crdt_type"
    | "/docs/concepts/container"
    | "/docs/concepts/crdt"
    | "/docs/concepts/cursor_stable_positions"
    | "/docs/concepts/event_graph_walker"
    | "/docs/concepts/frontiers"
    | "/docs/concepts/import_status"
    | "/docs/concepts/operations_changes"
    | "/docs/concepts/oplog_docstate"
    | "/docs/concepts/peerid_management"
    | "/docs/concepts/shallow_snapshots"
    | "/docs/concepts/transaction_model"
    | "/docs/concepts/version_vector"
    | "/docs/concepts/when_not_crdt"
    | "/docs/performance/docsize"
    | "/docs/performance/native"
    | "/docs/tutorial/composition"
    | "/docs/tutorial/counter"
    | "/docs/tutorial/cursor"
    | "/docs/tutorial/encoding"
    | "/docs/tutorial/ephemeral"
    | "/docs/tutorial/event"
    | "/docs/tutorial/get_started"
    | "/docs/tutorial/list"
    | "/docs/tutorial/loro_doc"
    | "/docs/tutorial/map"
    | "/docs/tutorial/persistence"
    | "/docs/tutorial/sync"
    | "/docs/tutorial/text"
    | "/docs/tutorial/time_travel"
    | "/docs/tutorial/tips"
    | "/docs/tutorial/tree"
    | "/docs/tutorial/version"
    | "/docs/performance"
    | "/changelog/inspector-v0/1/0"
    | "/changelog/v1/0/0-beta"
    | "/changelog/v1/1/0"
    | "/changelog/v1/2/0"
    | "/changelog/v1/3/0"
    | "/changelog/v1/4/0"
    | "/changelog/v1/4/7"
    | "/changelog/v1/5/0"
    | "/changelog/v1/6/0"
    | "/changelog/v1/8/0"
    | "/changelog/v1/9/0";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/discord"
    | "/blog/crdt-richtext"
    | "/blog/loro-mirror"
    | "/blog/loro-now-open-source"
    | "/blog/loro-open-source"
    | "/blog/loro-protocol"
    | "/blog/loro-richtext"
    | "/blog/movable-tree"
    | "/docs/examples"
    | "/docs/llm"
    | "/blog/"
    | "/changelog/"
    | "/docs/"
    | "/blog/v1/0"
    | "/docs/advanced/cid"
    | "/docs/advanced/doc_state_and_oplog"
    | "/docs/advanced/event_graph_walker"
    | "/docs/advanced/import_batch"
    | "/docs/advanced/inspector"
    | "/docs/advanced/jsonpath"
    | "/docs/advanced/op_and_change"
    | "/docs/advanced/replayable_event_graph"
    | "/docs/advanced/shallow_snapshot"
    | "/docs/advanced/timestamp"
    | "/docs/advanced/undo"
    | "/docs/advanced/version_deep_dive"
    | "/docs/api/js"
    | "/docs/concepts/attached_detached"
    | "/docs/concepts/choose_crdt_type"
    | "/docs/concepts/container"
    | "/docs/concepts/crdt"
    | "/docs/concepts/cursor_stable_positions"
    | "/docs/concepts/event_graph_walker"
    | "/docs/concepts/frontiers"
    | "/docs/concepts/import_status"
    | "/docs/concepts/operations_changes"
    | "/docs/concepts/oplog_docstate"
    | "/docs/concepts/peerid_management"
    | "/docs/concepts/shallow_snapshots"
    | "/docs/concepts/transaction_model"
    | "/docs/concepts/version_vector"
    | "/docs/concepts/when_not_crdt"
    | "/docs/performance/docsize"
    | "/docs/performance/native"
    | "/docs/tutorial/composition"
    | "/docs/tutorial/counter"
    | "/docs/tutorial/cursor"
    | "/docs/tutorial/encoding"
    | "/docs/tutorial/ephemeral"
    | "/docs/tutorial/event"
    | "/docs/tutorial/get_started"
    | "/docs/tutorial/list"
    | "/docs/tutorial/loro_doc"
    | "/docs/tutorial/map"
    | "/docs/tutorial/persistence"
    | "/docs/tutorial/sync"
    | "/docs/tutorial/text"
    | "/docs/tutorial/time_travel"
    | "/docs/tutorial/tips"
    | "/docs/tutorial/tree"
    | "/docs/tutorial/version"
    | "/docs/performance/"
    | "/changelog/inspector-v0/1/0"
    | "/changelog/v1/0/0-beta"
    | "/changelog/v1/1/0"
    | "/changelog/v1/2/0"
    | "/changelog/v1/3/0"
    | "/changelog/v1/4/0"
    | "/changelog/v1/4/7"
    | "/changelog/v1/5/0"
    | "/changelog/v1/6/0"
    | "/changelog/v1/8/0"
    | "/changelog/v1/9/0";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  DiscordRoute: typeof DiscordRoute;
  BlogCrdtRichtextRoute: typeof BlogCrdtRichtextRoute;
  BlogLoroMirrorRoute: typeof BlogLoroMirrorRoute;
  BlogLoroNowOpenSourceRoute: typeof BlogLoroNowOpenSourceRoute;
  BlogLoroOpenSourceRoute: typeof BlogLoroOpenSourceRoute;
  BlogLoroProtocolRoute: typeof BlogLoroProtocolRoute;
  BlogLoroRichtextRoute: typeof BlogLoroRichtextRoute;
  BlogMovableTreeRoute: typeof BlogMovableTreeRoute;
  DocsExamplesRoute: typeof DocsExamplesRoute;
  DocsLlmRoute: typeof DocsLlmRoute;
  BlogIndexRoute: typeof BlogIndexRoute;
  ChangelogIndexRoute: typeof ChangelogIndexRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
  BlogV10Route: typeof BlogV10Route;
  DocsAdvancedCidRoute: typeof DocsAdvancedCidRoute;
  DocsAdvancedDoc_state_and_oplogRoute: typeof DocsAdvancedDoc_state_and_oplogRoute;
  DocsAdvancedEvent_graph_walkerRoute: typeof DocsAdvancedEvent_graph_walkerRoute;
  DocsAdvancedImport_batchRoute: typeof DocsAdvancedImport_batchRoute;
  DocsAdvancedInspectorRoute: typeof DocsAdvancedInspectorRoute;
  DocsAdvancedJsonpathRoute: typeof DocsAdvancedJsonpathRoute;
  DocsAdvancedOp_and_changeRoute: typeof DocsAdvancedOp_and_changeRoute;
  DocsAdvancedReplayable_event_graphRoute: typeof DocsAdvancedReplayable_event_graphRoute;
  DocsAdvancedShallow_snapshotRoute: typeof DocsAdvancedShallow_snapshotRoute;
  DocsAdvancedTimestampRoute: typeof DocsAdvancedTimestampRoute;
  DocsAdvancedUndoRoute: typeof DocsAdvancedUndoRoute;
  DocsAdvancedVersion_deep_diveRoute: typeof DocsAdvancedVersion_deep_diveRoute;
  DocsApiJsRoute: typeof DocsApiJsRoute;
  DocsConceptsAttached_detachedRoute: typeof DocsConceptsAttached_detachedRoute;
  DocsConceptsChoose_crdt_typeRoute: typeof DocsConceptsChoose_crdt_typeRoute;
  DocsConceptsContainerRoute: typeof DocsConceptsContainerRoute;
  DocsConceptsCrdtRoute: typeof DocsConceptsCrdtRoute;
  DocsConceptsCursor_stable_positionsRoute: typeof DocsConceptsCursor_stable_positionsRoute;
  DocsConceptsEvent_graph_walkerRoute: typeof DocsConceptsEvent_graph_walkerRoute;
  DocsConceptsFrontiersRoute: typeof DocsConceptsFrontiersRoute;
  DocsConceptsImport_statusRoute: typeof DocsConceptsImport_statusRoute;
  DocsConceptsOperations_changesRoute: typeof DocsConceptsOperations_changesRoute;
  DocsConceptsOplog_docstateRoute: typeof DocsConceptsOplog_docstateRoute;
  DocsConceptsPeerid_managementRoute: typeof DocsConceptsPeerid_managementRoute;
  DocsConceptsShallow_snapshotsRoute: typeof DocsConceptsShallow_snapshotsRoute;
  DocsConceptsTransaction_modelRoute: typeof DocsConceptsTransaction_modelRoute;
  DocsConceptsVersion_vectorRoute: typeof DocsConceptsVersion_vectorRoute;
  DocsConceptsWhen_not_crdtRoute: typeof DocsConceptsWhen_not_crdtRoute;
  DocsPerformanceDocsizeRoute: typeof DocsPerformanceDocsizeRoute;
  DocsPerformanceNativeRoute: typeof DocsPerformanceNativeRoute;
  DocsTutorialCompositionRoute: typeof DocsTutorialCompositionRoute;
  DocsTutorialCounterRoute: typeof DocsTutorialCounterRoute;
  DocsTutorialCursorRoute: typeof DocsTutorialCursorRoute;
  DocsTutorialEncodingRoute: typeof DocsTutorialEncodingRoute;
  DocsTutorialEphemeralRoute: typeof DocsTutorialEphemeralRoute;
  DocsTutorialEventRoute: typeof DocsTutorialEventRoute;
  DocsTutorialGet_startedRoute: typeof DocsTutorialGet_startedRoute;
  DocsTutorialListRoute: typeof DocsTutorialListRoute;
  DocsTutorialLoro_docRoute: typeof DocsTutorialLoro_docRoute;
  DocsTutorialMapRoute: typeof DocsTutorialMapRoute;
  DocsTutorialPersistenceRoute: typeof DocsTutorialPersistenceRoute;
  DocsTutorialSyncRoute: typeof DocsTutorialSyncRoute;
  DocsTutorialTextRoute: typeof DocsTutorialTextRoute;
  DocsTutorialTime_travelRoute: typeof DocsTutorialTime_travelRoute;
  DocsTutorialTipsRoute: typeof DocsTutorialTipsRoute;
  DocsTutorialTreeRoute: typeof DocsTutorialTreeRoute;
  DocsTutorialVersionRoute: typeof DocsTutorialVersionRoute;
  DocsPerformanceIndexRoute: typeof DocsPerformanceIndexRoute;
  ChangelogInspectorV010Route: typeof ChangelogInspectorV010Route;
  ChangelogV100BetaRoute: typeof ChangelogV100BetaRoute;
  ChangelogV110Route: typeof ChangelogV110Route;
  ChangelogV120Route: typeof ChangelogV120Route;
  ChangelogV130Route: typeof ChangelogV130Route;
  ChangelogV140Route: typeof ChangelogV140Route;
  ChangelogV147Route: typeof ChangelogV147Route;
  ChangelogV150Route: typeof ChangelogV150Route;
  ChangelogV160Route: typeof ChangelogV160Route;
  ChangelogV180Route: typeof ChangelogV180Route;
  ChangelogV190Route: typeof ChangelogV190Route;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/discord": {
      id: "/discord";
      path: "/discord";
      fullPath: "/discord";
      preLoaderRoute: typeof DiscordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/docs";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/": {
      id: "/changelog/";
      path: "/changelog";
      fullPath: "/changelog/";
      preLoaderRoute: typeof ChangelogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/": {
      id: "/blog/";
      path: "/blog";
      fullPath: "/blog/";
      preLoaderRoute: typeof BlogIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/llm": {
      id: "/docs/llm";
      path: "/docs/llm";
      fullPath: "/docs/llm";
      preLoaderRoute: typeof DocsLlmRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/examples": {
      id: "/docs/examples";
      path: "/docs/examples";
      fullPath: "/docs/examples";
      preLoaderRoute: typeof DocsExamplesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/movable-tree": {
      id: "/blog/movable-tree";
      path: "/blog/movable-tree";
      fullPath: "/blog/movable-tree";
      preLoaderRoute: typeof BlogMovableTreeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/loro-richtext": {
      id: "/blog/loro-richtext";
      path: "/blog/loro-richtext";
      fullPath: "/blog/loro-richtext";
      preLoaderRoute: typeof BlogLoroRichtextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/loro-protocol": {
      id: "/blog/loro-protocol";
      path: "/blog/loro-protocol";
      fullPath: "/blog/loro-protocol";
      preLoaderRoute: typeof BlogLoroProtocolRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/loro-open-source": {
      id: "/blog/loro-open-source";
      path: "/blog/loro-open-source";
      fullPath: "/blog/loro-open-source";
      preLoaderRoute: typeof BlogLoroOpenSourceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/loro-now-open-source": {
      id: "/blog/loro-now-open-source";
      path: "/blog/loro-now-open-source";
      fullPath: "/blog/loro-now-open-source";
      preLoaderRoute: typeof BlogLoroNowOpenSourceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/loro-mirror": {
      id: "/blog/loro-mirror";
      path: "/blog/loro-mirror";
      fullPath: "/blog/loro-mirror";
      preLoaderRoute: typeof BlogLoroMirrorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/crdt-richtext": {
      id: "/blog/crdt-richtext";
      path: "/blog/crdt-richtext";
      fullPath: "/blog/crdt-richtext";
      preLoaderRoute: typeof BlogCrdtRichtextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/performance/": {
      id: "/docs/performance/";
      path: "/docs/performance";
      fullPath: "/docs/performance/";
      preLoaderRoute: typeof DocsPerformanceIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/version": {
      id: "/docs/tutorial/version";
      path: "/docs/tutorial/version";
      fullPath: "/docs/tutorial/version";
      preLoaderRoute: typeof DocsTutorialVersionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/tree": {
      id: "/docs/tutorial/tree";
      path: "/docs/tutorial/tree";
      fullPath: "/docs/tutorial/tree";
      preLoaderRoute: typeof DocsTutorialTreeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/tips": {
      id: "/docs/tutorial/tips";
      path: "/docs/tutorial/tips";
      fullPath: "/docs/tutorial/tips";
      preLoaderRoute: typeof DocsTutorialTipsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/time_travel": {
      id: "/docs/tutorial/time_travel";
      path: "/docs/tutorial/time_travel";
      fullPath: "/docs/tutorial/time_travel";
      preLoaderRoute: typeof DocsTutorialTime_travelRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/text": {
      id: "/docs/tutorial/text";
      path: "/docs/tutorial/text";
      fullPath: "/docs/tutorial/text";
      preLoaderRoute: typeof DocsTutorialTextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/sync": {
      id: "/docs/tutorial/sync";
      path: "/docs/tutorial/sync";
      fullPath: "/docs/tutorial/sync";
      preLoaderRoute: typeof DocsTutorialSyncRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/persistence": {
      id: "/docs/tutorial/persistence";
      path: "/docs/tutorial/persistence";
      fullPath: "/docs/tutorial/persistence";
      preLoaderRoute: typeof DocsTutorialPersistenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/map": {
      id: "/docs/tutorial/map";
      path: "/docs/tutorial/map";
      fullPath: "/docs/tutorial/map";
      preLoaderRoute: typeof DocsTutorialMapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/loro_doc": {
      id: "/docs/tutorial/loro_doc";
      path: "/docs/tutorial/loro_doc";
      fullPath: "/docs/tutorial/loro_doc";
      preLoaderRoute: typeof DocsTutorialLoro_docRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/list": {
      id: "/docs/tutorial/list";
      path: "/docs/tutorial/list";
      fullPath: "/docs/tutorial/list";
      preLoaderRoute: typeof DocsTutorialListRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/get_started": {
      id: "/docs/tutorial/get_started";
      path: "/docs/tutorial/get_started";
      fullPath: "/docs/tutorial/get_started";
      preLoaderRoute: typeof DocsTutorialGet_startedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/event": {
      id: "/docs/tutorial/event";
      path: "/docs/tutorial/event";
      fullPath: "/docs/tutorial/event";
      preLoaderRoute: typeof DocsTutorialEventRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/ephemeral": {
      id: "/docs/tutorial/ephemeral";
      path: "/docs/tutorial/ephemeral";
      fullPath: "/docs/tutorial/ephemeral";
      preLoaderRoute: typeof DocsTutorialEphemeralRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/encoding": {
      id: "/docs/tutorial/encoding";
      path: "/docs/tutorial/encoding";
      fullPath: "/docs/tutorial/encoding";
      preLoaderRoute: typeof DocsTutorialEncodingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/cursor": {
      id: "/docs/tutorial/cursor";
      path: "/docs/tutorial/cursor";
      fullPath: "/docs/tutorial/cursor";
      preLoaderRoute: typeof DocsTutorialCursorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/counter": {
      id: "/docs/tutorial/counter";
      path: "/docs/tutorial/counter";
      fullPath: "/docs/tutorial/counter";
      preLoaderRoute: typeof DocsTutorialCounterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/tutorial/composition": {
      id: "/docs/tutorial/composition";
      path: "/docs/tutorial/composition";
      fullPath: "/docs/tutorial/composition";
      preLoaderRoute: typeof DocsTutorialCompositionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/performance/native": {
      id: "/docs/performance/native";
      path: "/docs/performance/native";
      fullPath: "/docs/performance/native";
      preLoaderRoute: typeof DocsPerformanceNativeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/performance/docsize": {
      id: "/docs/performance/docsize";
      path: "/docs/performance/docsize";
      fullPath: "/docs/performance/docsize";
      preLoaderRoute: typeof DocsPerformanceDocsizeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/when_not_crdt": {
      id: "/docs/concepts/when_not_crdt";
      path: "/docs/concepts/when_not_crdt";
      fullPath: "/docs/concepts/when_not_crdt";
      preLoaderRoute: typeof DocsConceptsWhen_not_crdtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/version_vector": {
      id: "/docs/concepts/version_vector";
      path: "/docs/concepts/version_vector";
      fullPath: "/docs/concepts/version_vector";
      preLoaderRoute: typeof DocsConceptsVersion_vectorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/transaction_model": {
      id: "/docs/concepts/transaction_model";
      path: "/docs/concepts/transaction_model";
      fullPath: "/docs/concepts/transaction_model";
      preLoaderRoute: typeof DocsConceptsTransaction_modelRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/shallow_snapshots": {
      id: "/docs/concepts/shallow_snapshots";
      path: "/docs/concepts/shallow_snapshots";
      fullPath: "/docs/concepts/shallow_snapshots";
      preLoaderRoute: typeof DocsConceptsShallow_snapshotsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/peerid_management": {
      id: "/docs/concepts/peerid_management";
      path: "/docs/concepts/peerid_management";
      fullPath: "/docs/concepts/peerid_management";
      preLoaderRoute: typeof DocsConceptsPeerid_managementRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/oplog_docstate": {
      id: "/docs/concepts/oplog_docstate";
      path: "/docs/concepts/oplog_docstate";
      fullPath: "/docs/concepts/oplog_docstate";
      preLoaderRoute: typeof DocsConceptsOplog_docstateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/operations_changes": {
      id: "/docs/concepts/operations_changes";
      path: "/docs/concepts/operations_changes";
      fullPath: "/docs/concepts/operations_changes";
      preLoaderRoute: typeof DocsConceptsOperations_changesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/import_status": {
      id: "/docs/concepts/import_status";
      path: "/docs/concepts/import_status";
      fullPath: "/docs/concepts/import_status";
      preLoaderRoute: typeof DocsConceptsImport_statusRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/frontiers": {
      id: "/docs/concepts/frontiers";
      path: "/docs/concepts/frontiers";
      fullPath: "/docs/concepts/frontiers";
      preLoaderRoute: typeof DocsConceptsFrontiersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/event_graph_walker": {
      id: "/docs/concepts/event_graph_walker";
      path: "/docs/concepts/event_graph_walker";
      fullPath: "/docs/concepts/event_graph_walker";
      preLoaderRoute: typeof DocsConceptsEvent_graph_walkerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/cursor_stable_positions": {
      id: "/docs/concepts/cursor_stable_positions";
      path: "/docs/concepts/cursor_stable_positions";
      fullPath: "/docs/concepts/cursor_stable_positions";
      preLoaderRoute: typeof DocsConceptsCursor_stable_positionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/crdt": {
      id: "/docs/concepts/crdt";
      path: "/docs/concepts/crdt";
      fullPath: "/docs/concepts/crdt";
      preLoaderRoute: typeof DocsConceptsCrdtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/container": {
      id: "/docs/concepts/container";
      path: "/docs/concepts/container";
      fullPath: "/docs/concepts/container";
      preLoaderRoute: typeof DocsConceptsContainerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/choose_crdt_type": {
      id: "/docs/concepts/choose_crdt_type";
      path: "/docs/concepts/choose_crdt_type";
      fullPath: "/docs/concepts/choose_crdt_type";
      preLoaderRoute: typeof DocsConceptsChoose_crdt_typeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/concepts/attached_detached": {
      id: "/docs/concepts/attached_detached";
      path: "/docs/concepts/attached_detached";
      fullPath: "/docs/concepts/attached_detached";
      preLoaderRoute: typeof DocsConceptsAttached_detachedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/api/js": {
      id: "/docs/api/js";
      path: "/docs/api/js";
      fullPath: "/docs/api/js";
      preLoaderRoute: typeof DocsApiJsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/version_deep_dive": {
      id: "/docs/advanced/version_deep_dive";
      path: "/docs/advanced/version_deep_dive";
      fullPath: "/docs/advanced/version_deep_dive";
      preLoaderRoute: typeof DocsAdvancedVersion_deep_diveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/undo": {
      id: "/docs/advanced/undo";
      path: "/docs/advanced/undo";
      fullPath: "/docs/advanced/undo";
      preLoaderRoute: typeof DocsAdvancedUndoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/timestamp": {
      id: "/docs/advanced/timestamp";
      path: "/docs/advanced/timestamp";
      fullPath: "/docs/advanced/timestamp";
      preLoaderRoute: typeof DocsAdvancedTimestampRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/shallow_snapshot": {
      id: "/docs/advanced/shallow_snapshot";
      path: "/docs/advanced/shallow_snapshot";
      fullPath: "/docs/advanced/shallow_snapshot";
      preLoaderRoute: typeof DocsAdvancedShallow_snapshotRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/replayable_event_graph": {
      id: "/docs/advanced/replayable_event_graph";
      path: "/docs/advanced/replayable_event_graph";
      fullPath: "/docs/advanced/replayable_event_graph";
      preLoaderRoute: typeof DocsAdvancedReplayable_event_graphRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/op_and_change": {
      id: "/docs/advanced/op_and_change";
      path: "/docs/advanced/op_and_change";
      fullPath: "/docs/advanced/op_and_change";
      preLoaderRoute: typeof DocsAdvancedOp_and_changeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/jsonpath": {
      id: "/docs/advanced/jsonpath";
      path: "/docs/advanced/jsonpath";
      fullPath: "/docs/advanced/jsonpath";
      preLoaderRoute: typeof DocsAdvancedJsonpathRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/inspector": {
      id: "/docs/advanced/inspector";
      path: "/docs/advanced/inspector";
      fullPath: "/docs/advanced/inspector";
      preLoaderRoute: typeof DocsAdvancedInspectorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/import_batch": {
      id: "/docs/advanced/import_batch";
      path: "/docs/advanced/import_batch";
      fullPath: "/docs/advanced/import_batch";
      preLoaderRoute: typeof DocsAdvancedImport_batchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/event_graph_walker": {
      id: "/docs/advanced/event_graph_walker";
      path: "/docs/advanced/event_graph_walker";
      fullPath: "/docs/advanced/event_graph_walker";
      preLoaderRoute: typeof DocsAdvancedEvent_graph_walkerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/doc_state_and_oplog": {
      id: "/docs/advanced/doc_state_and_oplog";
      path: "/docs/advanced/doc_state_and_oplog";
      fullPath: "/docs/advanced/doc_state_and_oplog";
      preLoaderRoute: typeof DocsAdvancedDoc_state_and_oplogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/advanced/cid": {
      id: "/docs/advanced/cid";
      path: "/docs/advanced/cid";
      fullPath: "/docs/advanced/cid";
      preLoaderRoute: typeof DocsAdvancedCidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/blog/v1/0": {
      id: "/blog/v1/0";
      path: "/blog/v1/0";
      fullPath: "/blog/v1/0";
      preLoaderRoute: typeof BlogV10RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/9/0": {
      id: "/changelog/v1/9/0";
      path: "/changelog/v1/9/0";
      fullPath: "/changelog/v1/9/0";
      preLoaderRoute: typeof ChangelogV190RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/8/0": {
      id: "/changelog/v1/8/0";
      path: "/changelog/v1/8/0";
      fullPath: "/changelog/v1/8/0";
      preLoaderRoute: typeof ChangelogV180RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/6/0": {
      id: "/changelog/v1/6/0";
      path: "/changelog/v1/6/0";
      fullPath: "/changelog/v1/6/0";
      preLoaderRoute: typeof ChangelogV160RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/5/0": {
      id: "/changelog/v1/5/0";
      path: "/changelog/v1/5/0";
      fullPath: "/changelog/v1/5/0";
      preLoaderRoute: typeof ChangelogV150RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/4/7": {
      id: "/changelog/v1/4/7";
      path: "/changelog/v1/4/7";
      fullPath: "/changelog/v1/4/7";
      preLoaderRoute: typeof ChangelogV147RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/4/0": {
      id: "/changelog/v1/4/0";
      path: "/changelog/v1/4/0";
      fullPath: "/changelog/v1/4/0";
      preLoaderRoute: typeof ChangelogV140RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/3/0": {
      id: "/changelog/v1/3/0";
      path: "/changelog/v1/3/0";
      fullPath: "/changelog/v1/3/0";
      preLoaderRoute: typeof ChangelogV130RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/2/0": {
      id: "/changelog/v1/2/0";
      path: "/changelog/v1/2/0";
      fullPath: "/changelog/v1/2/0";
      preLoaderRoute: typeof ChangelogV120RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/1/0": {
      id: "/changelog/v1/1/0";
      path: "/changelog/v1/1/0";
      fullPath: "/changelog/v1/1/0";
      preLoaderRoute: typeof ChangelogV110RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/v1/0/0-beta": {
      id: "/changelog/v1/0/0-beta";
      path: "/changelog/v1/0/0-beta";
      fullPath: "/changelog/v1/0/0-beta";
      preLoaderRoute: typeof ChangelogV100BetaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog/inspector-v0/1/0": {
      id: "/changelog/inspector-v0/1/0";
      path: "/changelog/inspector-v0/1/0";
      fullPath: "/changelog/inspector-v0/1/0";
      preLoaderRoute: typeof ChangelogInspectorV010RouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscordRoute: DiscordRoute,
  BlogCrdtRichtextRoute: BlogCrdtRichtextRoute,
  BlogLoroMirrorRoute: BlogLoroMirrorRoute,
  BlogLoroNowOpenSourceRoute: BlogLoroNowOpenSourceRoute,
  BlogLoroOpenSourceRoute: BlogLoroOpenSourceRoute,
  BlogLoroProtocolRoute: BlogLoroProtocolRoute,
  BlogLoroRichtextRoute: BlogLoroRichtextRoute,
  BlogMovableTreeRoute: BlogMovableTreeRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsLlmRoute: DocsLlmRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  BlogV10Route: BlogV10Route,
  DocsAdvancedCidRoute: DocsAdvancedCidRoute,
  DocsAdvancedDoc_state_and_oplogRoute: DocsAdvancedDoc_state_and_oplogRoute,
  DocsAdvancedEvent_graph_walkerRoute: DocsAdvancedEvent_graph_walkerRoute,
  DocsAdvancedImport_batchRoute: DocsAdvancedImport_batchRoute,
  DocsAdvancedInspectorRoute: DocsAdvancedInspectorRoute,
  DocsAdvancedJsonpathRoute: DocsAdvancedJsonpathRoute,
  DocsAdvancedOp_and_changeRoute: DocsAdvancedOp_and_changeRoute,
  DocsAdvancedReplayable_event_graphRoute:
    DocsAdvancedReplayable_event_graphRoute,
  DocsAdvancedShallow_snapshotRoute: DocsAdvancedShallow_snapshotRoute,
  DocsAdvancedTimestampRoute: DocsAdvancedTimestampRoute,
  DocsAdvancedUndoRoute: DocsAdvancedUndoRoute,
  DocsAdvancedVersion_deep_diveRoute: DocsAdvancedVersion_deep_diveRoute,
  DocsApiJsRoute: DocsApiJsRoute,
  DocsConceptsAttached_detachedRoute: DocsConceptsAttached_detachedRoute,
  DocsConceptsChoose_crdt_typeRoute: DocsConceptsChoose_crdt_typeRoute,
  DocsConceptsContainerRoute: DocsConceptsContainerRoute,
  DocsConceptsCrdtRoute: DocsConceptsCrdtRoute,
  DocsConceptsCursor_stable_positionsRoute:
    DocsConceptsCursor_stable_positionsRoute,
  DocsConceptsEvent_graph_walkerRoute: DocsConceptsEvent_graph_walkerRoute,
  DocsConceptsFrontiersRoute: DocsConceptsFrontiersRoute,
  DocsConceptsImport_statusRoute: DocsConceptsImport_statusRoute,
  DocsConceptsOperations_changesRoute: DocsConceptsOperations_changesRoute,
  DocsConceptsOplog_docstateRoute: DocsConceptsOplog_docstateRoute,
  DocsConceptsPeerid_managementRoute: DocsConceptsPeerid_managementRoute,
  DocsConceptsShallow_snapshotsRoute: DocsConceptsShallow_snapshotsRoute,
  DocsConceptsTransaction_modelRoute: DocsConceptsTransaction_modelRoute,
  DocsConceptsVersion_vectorRoute: DocsConceptsVersion_vectorRoute,
  DocsConceptsWhen_not_crdtRoute: DocsConceptsWhen_not_crdtRoute,
  DocsPerformanceDocsizeRoute: DocsPerformanceDocsizeRoute,
  DocsPerformanceNativeRoute: DocsPerformanceNativeRoute,
  DocsTutorialCompositionRoute: DocsTutorialCompositionRoute,
  DocsTutorialCounterRoute: DocsTutorialCounterRoute,
  DocsTutorialCursorRoute: DocsTutorialCursorRoute,
  DocsTutorialEncodingRoute: DocsTutorialEncodingRoute,
  DocsTutorialEphemeralRoute: DocsTutorialEphemeralRoute,
  DocsTutorialEventRoute: DocsTutorialEventRoute,
  DocsTutorialGet_startedRoute: DocsTutorialGet_startedRoute,
  DocsTutorialListRoute: DocsTutorialListRoute,
  DocsTutorialLoro_docRoute: DocsTutorialLoro_docRoute,
  DocsTutorialMapRoute: DocsTutorialMapRoute,
  DocsTutorialPersistenceRoute: DocsTutorialPersistenceRoute,
  DocsTutorialSyncRoute: DocsTutorialSyncRoute,
  DocsTutorialTextRoute: DocsTutorialTextRoute,
  DocsTutorialTime_travelRoute: DocsTutorialTime_travelRoute,
  DocsTutorialTipsRoute: DocsTutorialTipsRoute,
  DocsTutorialTreeRoute: DocsTutorialTreeRoute,
  DocsTutorialVersionRoute: DocsTutorialVersionRoute,
  DocsPerformanceIndexRoute: DocsPerformanceIndexRoute,
  ChangelogInspectorV010Route: ChangelogInspectorV010Route,
  ChangelogV100BetaRoute: ChangelogV100BetaRoute,
  ChangelogV110Route: ChangelogV110Route,
  ChangelogV120Route: ChangelogV120Route,
  ChangelogV130Route: ChangelogV130Route,
  ChangelogV140Route: ChangelogV140Route,
  ChangelogV147Route: ChangelogV147Route,
  ChangelogV150Route: ChangelogV150Route,
  ChangelogV160Route: ChangelogV160Route,
  ChangelogV180Route: ChangelogV180Route,
  ChangelogV190Route: ChangelogV190Route,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
